# Generated by Django 5.1.6 on 2025-02-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('vehicles', '0008_remove_vehicle_broker_remove_vehicle_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='account',
        ),
        migrations.RemoveField(
            model_name='ziuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='ziuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Broker',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='ZiUser',
        ),
    ]
