# Generated by Django 5.1.6 on 2025-02-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ziuser',
            options={},
        ),
    ]
