# Generated by Django 5.1.6 on 2025-02-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_ziuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ziuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
