# Generated by Django 5.1.6 on 2025-02-11 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_ziuser_options'),
        ('vehicles', '0008_remove_vehicle_broker_remove_vehicle_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ziuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('active', models.BooleanField()),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.broker')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='interested_cars',
            field=models.ManyToManyField(related_name='customers_interesed', through='user_auth.VehicleInterest', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='broker',
            name='interest_cars',
            field=models.ManyToManyField(related_name='brokers_interesed', through='user_auth.VehicleInterest', to='vehicles.vehicle'),
        ),
    ]
