# Generated by Django 5.1.6 on 2025-02-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_alter_ziuser_options_broker_customer_vehicleinterest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinterest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
