# Generated by Django 5.1.6 on 2025-02-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_vehicleinterest_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ziuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
