# Generated by Django 5.1.6 on 2025-02-12 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_alter_broker_account_alter_customer_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinterest',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.broker', verbose_name='Through Broker'),
        ),
    ]
