# Generated by Django 5.1.6 on 2025-02-12 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_alter_vehicleinterest_broker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinterest',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.broker', verbose_name='Through Broker'),
        ),
        migrations.AlterField(
            model_name='vehicleinterest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.customer', verbose_name='Interested Customer'),
        ),
        migrations.AlterField(
            model_name='vehicleinterest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
