# Generated by Django 5.1.6 on 2025-02-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_alter_vehicleinterest_broker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ziuser',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ziuser',
            name='rating',
        ),
        migrations.AddField(
            model_name='broker',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
