# Generated by Django 5.1.6 on 2025-02-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0012_remove_ziuser_notes_remove_ziuser_rating_broker_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='broker',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
