# Generated by Django 5.1.6 on 2025-02-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0013_alter_broker_name_alter_broker_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ziuser',
            options={'verbose_name': 'User Account', 'verbose_name_plural': 'User Accounts'},
        ),
        migrations.RemoveField(
            model_name='ziuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='broker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
