# Generated by Django 5.1.6 on 2025-02-17 17:24

import general.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0014_alter_ziuser_options_remove_ziuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, validators=[general.validators.validate_ethiopian_phone_number]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, validators=[general.validators.validate_ethiopian_phone_number]),
        ),
    ]
