# Generated by Django 5.1.6 on 2025-02-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_frozen_alter_producer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='top_speed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Top Speed'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='zero_to_hundered',
            field=models.FloatField(blank=True, null=True, verbose_name='0 To 100 Accelaration'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='condition_check',
            field=models.BooleanField(blank=True, choices=[(True, 'Fully Checked'), (False, 'Not-Fully Checked')], null=True),
        ),
    ]
