# Generated by Django 5.1.6 on 2025-02-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_top_speed_vehicle_zero_to_hundered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='logo',
        ),
        migrations.AlterField(
            model_name='featuretype',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/feature-type-logos'),
        ),
    ]
