# Generated by Django 5.1.6 on 2025-02-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_remove_vehicle_images_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='VehicleImage',
        ),
    ]
