# Generated by Django 5.1.6 on 2025-02-11 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('vehicles', '0006_rename_image_vehicleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_cars', to='user_auth.broker'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_cars', to='user_auth.customer'),
        ),
    ]
