# Generated by Django 5.1.6 on 2025-02-11 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_ziuser_phone_number'),
        ('vehicles', '0008_remove_vehicle_broker_remove_vehicle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_cars', to='user_auth.broker'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_cars', to='user_auth.customer'),
        ),
    ]
