# Generated by Django 5.1.6 on 2025-02-11 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_vehicle_broker_vehicle_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuretype',
            name='logo',
        ),
    ]
