# Generated by Django 5.1.6 on 2025-02-11 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_remove_featuretype_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='cylinder_number',
            field=models.SmallIntegerField(blank=True, choices=[(3, '3'), (4, '4'), (6, '6'), (8, '8'), (12, '12'), (16, '16')], null=True, validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(3)], verbose_name='Cylinder Number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(99999)], verbose_name='Plate Number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_ownership',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('ተላላፊ', 'ተላላፊ')], max_length=5, null=True, verbose_name='Type of Plate Number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='production_year',
            field=models.PositiveIntegerField(blank=True, choices=[(1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')], null=True, validators=[django.core.validators.MaxValueValidator(2025), django.core.validators.MinValueValidator(1995)], verbose_name='Production Year'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seat_size',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)], verbose_name='Number Of Seats'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='zero_to_hundered',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(2)], verbose_name='Accelaration (0 To 100)'),
        ),
    ]
