# Generated by Django 5.1.6 on 2025-02-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0014_vehicle_offroad_alter_feature_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='logo',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='logos/vehicle-producers/'),
        ),
    ]
