# Generated by Django 5.1.6 on 2025-02-13 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_alter_producer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='cylinder_number',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(3)], verbose_name='Cylinder Number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_ownership',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Type of Plate Number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='State Of Issued Plated'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='production_country',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Production Country'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='production_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2025), django.core.validators.MinValueValidator(1995)], verbose_name='Production Year'),
        ),
    ]
