# Generated by Django 5.1.6 on 2025-02-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_alter_vehicle_cylinder_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(max_length=20, null=True, verbose_name='Body Type'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(max_length=20, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='condition',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='condition_check',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(max_length=20, null=True, verbose_name='Fuel'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(max_length=20, null=True, verbose_name='Transmission'),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.FileField(max_length=300, upload_to='vehicles/images/'),
        ),
    ]
