# Generated by Django 5.1.6 on 2025-02-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0017_alter_vehicle_body_type_alter_vehicle_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
