# Generated by Django 5.1.6 on 2025-02-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(choices=[('BK', 'Black'), ('WT', 'White'), ('SV', 'Silver'), ('RD', 'Red'), ('BL', 'Blue'), ('GY', 'Gray'), ('BG', 'Beige'), ('BN', 'Brown'), ('BZ', 'Bronze'), ('CA', 'Caramel'), ('CH', 'Charcoal'), ('CP', 'Copper'), ('CY', 'Cyan'), ('EM', 'Emerald'), ('FC', 'Fuchsia'), ('GD', 'Gold'), ('GN', 'Green'), ('IV', 'Ivory'), ('LM', 'Lime'), ('MT', 'Mint'), ('NV', 'Navy'), ('OG', 'Orange'), ('PN', 'Pink'), ('PU', 'Purple'), ('TQ', 'Turquoise'), ('YL', 'Yellow'), ('NN', 'Other')], max_length=20, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('BN', 'Benzene'), ('DS', 'Diesel'), ('EL', 'Electric'), ('HY', 'Hybrid'), ('NN', 'Other')], max_length=20, null=True, verbose_name='Fuel'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price_negotiability',
            field=models.BooleanField(null=True, verbose_name='Negotiable'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='production_country',
            field=models.CharField(blank=True, choices=[('JP', 'Japan'), ('US', 'United States'), ('DE', 'Germany'), ('CN', 'China'), ('IN', 'India'), ('IT', 'Italy'), ('MX', 'Mexico'), ('KR', 'South Korea'), ('BR', 'Brazil'), ('FR', 'France'), ('ES', 'Spain'), ('CA', 'Canada'), ('UK', 'United Kingdom'), ('RU', 'Russia'), ('TR', 'Turkey'), ('NN', 'Other')], max_length=10, null=True, verbose_name='Production Country'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('AU', 'Automatic'), ('MN', 'Manual'), ('SM', 'Semi-Auto'), ('NN', 'Other')], max_length=20, null=True, verbose_name='Transmission'),
        ),
    ]
